obj-y := common.o pci.o rps-irq.o rps-timer.o localtimer.o 

obj-$(CONFIG_SMP)			+= platsmp.o headsmp.o
obj-$(CONFIG_HOTPLUG_CPU)		+= hotplug.o
obj-$(CONFIG_MACH_POGOPLUGV3)		+= pogoplugv3-setup.o
obj-$(CONFIG_MACH_POGOPLUGV3PCI)	+= pogoplugv3pci-setup.o
obj-$(CONFIG_MACH_MLP89626)		+= mlp89626-setup.o
obj-$(CONFIG_MACH_IOMEGAHMNDCE)		== iomegahmndce-setup.o
